export const RECEIVE_SELLER = 'receive_seller'
export const RECEIVE_RATINGS = 'receive_ratings'
export const RECEIVE_GOODS = 'receive_goods'
export const CLEAR_CART = 'clear_cart'
export const UPDATE_COUNT = 'update_count'
export const SET_FOOD = 'set_food'
export const SWITCH_ONLY_CONTENT = 'switch_only_content'
export const SET_SELECT_TYPE = 'set_select_type'